select 
brand,
'Shopify' as platform_name,
'Upscribe' as order_channel,
{{store_name('store')}},
cast(subscription_id as string) subscription_id,
shopify_customer_id as customer_id,
utm_source,
utm_medium,
date(created_at) created_at,
product_id as external_product_id,
items_variant_id as external_variant_id,
cast(null as date) as next_charge_scheduled_at,
cast(order_interval_frequency as string) order_interval_frequency,
cast(null as string) as order_interval_unit,
cast(null as string) as product_title,
quantity,
items_sku as sku,
cast(null as string) as status,
date(cast(updated_at as timestamp)) updated_at,
cancellation_reason,
cancelled_on as cancelled_at,
cast(null as int) as order_day_of_month,
cast(null as string) as presentment_currency,
cancellation_comment as cancellation_reason_comments,
_daton_batch_runtime
from {{ref('UpscribeSubscriptionItems')}} 