Select 
brand,
store_name,
platform_name,
order_date,
currency_code,
purchase_order_number,
product_id,
sku,
vendor_id,
sum(netcost_amount) netcost_amount,
sum(listprice_amount) listprice_amount,
sum(ordered_quantity_amount) ordered_quantity_amount,
sum(open_po_accepted_quantity_amount) open_po_accepted_quantity_amount,
sum(closed_po_accepted_quantity_amount) closed_po_accepted_quantity_amount,
sum(open_po_rejected_quantity_amount) open_po_rejected_quantity_amount,
sum(closed_po_rejected_quantity_amount) closed_po_rejected_quantity_amount,
sum(open_po_received_quantity_amount) open_po_received_quantity_amount,
sum(closed_po_received_quantity_amount) closed_po_received_quantity_amount
from (
    select
    brand,
    marketplaceName as store_name,
    buyerProductIdentifier as product_id,
    '' as sku,
    vendorid as vendor_id,
    cast(purchaseOrderDate as date) as order_date,
    exchange_currency_code as currency_code,
    'Amazon Vendor Central' as platform_name,
    purchaseOrderNumber as purchase_order_number,
    round((netcost_amount/exchange_currency_rate),2) as netcost_amount,
    round((listprice_amount/exchange_currency_rate),2) as listprice_amount,
    round((ordered_quantity_amount/exchange_currency_rate),2) as ordered_quantity_amount,
    case when purchaseOrderStatus = 'OPEN' then accepted_quantity_amount else 0 end as open_po_accepted_quantity_amount,
    case when purchaseOrderStatus = 'CLOSED' then accepted_quantity_amount else 0 end as closed_po_accepted_quantity_amount,
    case when purchaseOrderStatus = 'OPEN' then rejected_quantity_amount else 0 end as open_po_rejected_quantity_amount,
    case when purchaseOrderStatus = 'CLOSED' then rejected_quantity_amount else 0 end as closed_po_rejected_quantity_amount,
    case when purchaseOrderStatus = 'OPEN' then received_quantity_amount else 0 end as open_po_received_quantity_amount,
    case when purchaseOrderStatus = 'CLOSED' then received_quantity_amount else 0 end as closed_po_received_quantity_amount
    from {{ ref('RetailProcurementOrdersStatus') }}
    ) group by 1,2,3,4,5,6,7,8,9