select 
brand_name,
platform_name,
store_name,
product_id,
product_name,
sku,
date,
item_total_price as this_day_item_total_price,
LAG(item_total_price,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_item_total_price,
item_total_price - LAG(item_total_price,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_item_total_price,
LAG(item_total_price,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_item_total_price,
item_total_price - LAG(item_total_price,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_item_total_price,
organic_sales as this_day_organic_sales,
LAG(organic_sales,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_organic_sales,
organic_sales - LAG(organic_sales,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_organic_sales,
LAG(organic_sales,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_organic_sales,
organic_sales - LAG(organic_sales,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_organic_sales,
adsales as this_day_adsales,
LAG(adsales,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_adsales,
adsales - LAG(adsales,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_adsales,
LAG(adsales,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_adsales,
adsales - LAG(adsales,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_adsales,
adspend as this_day_adspend,
LAG(adspend,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_adspend,
adspend - LAG(adspend,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_adspend,
LAG(adspend,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_adspend,
adspend - LAG(adspend,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_adspend,
quantity as this_day_quantity,
LAG(quantity,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_quantity,
quantity - LAG(quantity,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_quantity,
LAG(quantity,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_quantity,
quantity - LAG(quantity,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_quantity,
net_quantity as this_day_net_quantity,
LAG(net_quantity,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_net_quantity,
net_quantity - LAG(net_quantity,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_net_quantity,
LAG(net_quantity,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_net_quantity,
net_quantity - LAG(net_quantity,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_net_quantity,
sessions as this_day_sessions,
LAG(sessions,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_sessions,
sessions - LAG(sessions,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_sessions,
LAG(sessions,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_sessions,
sessions - LAG(sessions,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_sessions,
page_views as this_day_page_views,
LAG(page_views,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_day_page_views,
page_views - LAG(page_views,1) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) daily_change_page_views,
LAG(page_views,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) last_year_page_views,
page_views - LAG(page_views,365) OVER (PARTITION BY brand_name, platform_name, store_name, product_id, product_name, sku ORDER BY date) yearly_change_page_views
from {{ ref('sales_deepdive')}}