select 
'Flipkart' as platform_name,
coalesce(fsn,'') product_id,
Product_Title_Description as description,
cast(null as string) as category, 
cast(null as string) as sub_category, 
cast(null as numeric) as mrp, 
cast(null as numeric) as cogs, 
cast(null as string) as currency_code,
cast(null as date) as start_date, 
cast(null as date) as end_date,
coalesce(sku,'') sku,
coalesce(cast(null as string),'') product_name,
'' as color, 
coalesce(cast(null as string),'') seller,
coalesce(cast(null as string),'') size,
cast(null as string) product_category,
cast(null as string) as ASINstatus,
cast(null as numeric) as buybox_landed_price,
cast(null as numeric) as buybox_listing_price,
cast(null as string) as buybox_seller_id,
_daton_batch_runtime 
from {{ ref('FlipkartSalesReport') }}